# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11d72d9e8d6e7ffae3d516ff1568ea97fb58bcc918476e20306cee584cfafe4aa6a57d1dbb77a0df3ed811cbbfd1c2afe4519363d2c9e08440d7f4b0b7a5dd0e

test:
  secret_key_base: 1ae39a76dfd1c1c0dff1bdae1cbef0f37632a8c85f6125bd94818a16097257d7ac79b68fa5424e6b6aee3e68c41bdb3088a6b823f5ac15470da38694e6066156

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
